
export interface Theme {
  name: string;
  fontFamily: string;
  fontColor: string;
  backgroundColor: string;
  slideBackgroundColor: string;
  accentColor: string;
  gradientBackground?: string;
  sidebarColor?: string;
  navbarColor?: string;
  type: 'light' | 'dark';
}

export const themes: Theme[] = [
  {
    name: 'Arctic Aurora',
    fontFamily: '"Roboto", sans-serif',
    fontColor: '#e2e8f0',
    backgroundColor: '#0f172a',
    slideBackgroundColor: '#1e293b',
    accentColor: '#38bdf8',
    gradientBackground: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
    navbarColor: '#1e293b',
    sidebarColor: '#0f172a',
    type: 'dark',
  },
  {
    name: 'Sakura Blossom',
    fontFamily: '"Noto Sans JP", sans-serif',
    fontColor: '#5d576b',
    backgroundColor: '#fff5f5',
    slideBackgroundColor: '#ffffff',
    accentColor: '#f687b3',
    gradientBackground: 'linear-gradient(135deg, #fff5f5 0%, #fed7e2 100%)',
    navbarColor: '#fed7e2',
    sidebarColor: '#fff5f5', // This was inferred as it was cut off in the image but follows the pattern
    type: 'light', // This was inferred as it was cut off in the image but follows the pattern
  },
  {
    name: 'Lavender Mist',
    fontFamily: '"Nunito", sans-serif',
    fontColor: '#4a4e69',
    backgroundColor: '#f3e8ff',
    slideBackgroundColor: '#ffffff',
    accentColor: '#9f7aea',
    gradientBackground: 'linear-gradient(135deg, #f3e8ff 0%, #e9d5ff 100%)',
    navbarColor: '#e9d5ff',
    sidebarColor: '#f3e8ff',
    type: 'light',
  },
  {
    name: 'Golden Hour',
    fontFamily: '"Source Sans Pro", sans-serif',
    fontColor: '#3d3d3d',
    backgroundColor: '#fef3c7',
    slideBackgroundColor: '#ffffff',
    accentColor: '#f59e0b',
    gradientBackground: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)',
    navbarColor: '#fde68a',
    sidebarColor: '#fef3c7',
    type: 'light', // This was inferred as it was cut off in the image but follows the pattern
  },
  {
    name: 'Neon Cyberpunk',
    fontFamily: "'Rajdhani', sans-serif",
    fontColor: '#ffffff',
    backgroundColor: '#09090b',
    slideBackgroundColor: '#18181b',
    accentColor: '#22d3ee',
    gradientBackground: 'linear-gradient(135deg, #09090b 0%, #18181b 100%)',
    navbarColor: '#18181b',
    sidebarColor: '#09090b',
    type: 'dark',
  },
  {
    name: 'Coral Sunset',
    fontFamily: '"Raleway", sans-serif',
    fontColor: '#33272a',
    backgroundColor: '#feefaf',
    slideBackgroundColor: '#ffffff',
    accentColor: '#ff9a8b',
    gradientBackground: 'linear-gradient(135deg, #feefaf 0%, #ff9a8b 100%)',
    navbarColor: '#feefaf',
    sidebarColor: '#fff0f5', // Note: This appears to be a typo in the image, likely meant to be #feefaf or a similar color. I've used what's in the image.
    type: 'light',
  },
  {
    name: 'Emerald City',
    fontFamily: '"Montserrat", sans-serif',
    fontColor: '#ffffff',
    backgroundColor: '#064e3b',
    slideBackgroundColor: '#065f46',
    accentColor: '#34d399',
    gradientBackground: 'linear-gradient(135deg, #064e3b 0%, #065f46 100%)',
    navbarColor: '#065f46',
    sidebarColor: '#064e3b',
    type: 'dark',
  },
  {
    name: 'Neon Nights',
    fontFamily: '"Orbitron", sans-serif',
    fontColor: '#ffffff',
    backgroundColor: '#000000',
    slideBackgroundColor: '#1a1a1a',
    accentColor: '#00ff00',
    gradientBackground: 'linear-gradient(135deg, #000000 0%, #1a1a1a 100%)',
    navbarColor: '#1a1a1a',
    sidebarColor: '#000000',
    type: 'dark',
  },
  {
    name: 'Earthy Tones',
    fontFamily: '"Nunito", sans-serif',
    fontColor: '#3d3d3d',
    backgroundColor: '#d7ccc8',
    slideBackgroundColor: '#f5f5f5',
    accentColor: '#795548',
    gradientBackground: 'linear-gradient(135deg, #d7ccc8 0%, #a1887f 100%)',
    navbarColor: '#a1887f',
    sidebarColor: '#d7ccc8',
    type: 'light', // Inferred
  },
  {
    name: 'Sunset Glow',
    fontFamily: '"Merriweather", serif',
    fontColor: '#3d3d3d',
    backgroundColor: '#ffd700',
    slideBackgroundColor: '#ffffff',
    accentColor: '#ff6b6b',
    gradientBackground: 'linear-gradient(135deg, #ffd700 0%, #ff6b6b 100%)',
    navbarColor: '#ff6b6b',
    sidebarColor: '#ffd700',
    type: 'light',
  },
  {
    name: 'Minimalist Mono',
    fontFamily: '"IBM Plex Mono", monospace',
    fontColor: '#000000',
    backgroundColor: '#ffffff',
    slideBackgroundColor: '#f5f5f5',
    accentColor: '#000000',
    navbarColor: '#f5f5f5',
    sidebarColor: '#ffffff',
    type: 'light',
  },
  {
    name: 'Pastel Dream',
    fontFamily: '"Lato", sans-serif',
    fontColor: '#4a4e69',
    backgroundColor: '#f7e8e8',
    slideBackgroundColor: '#ffffff',
    accentColor: '#b5838d',
    gradientBackground: 'linear-gradient(135deg, #f7e8e8 0%, #e5cece 100%)',
    navbarColor: '#e5cece',
    sidebarColor: '#f7e8e8',
    type: 'light',
  },
  {
    name: 'Ocean Breeze',
    fontFamily: '"Open Sans", sans-serif',
    fontColor: '#f0f8ff',
    backgroundColor: '#0077be',
    slideBackgroundColor: '#ffffff',
    accentColor: '#00a86b',
    gradientBackground: 'linear-gradient(135deg, #0077be 0%, #00a86b 100%)',
    navbarColor: '#0077be',
    sidebarColor: '#005c8f', // Note: Sidebar color here is #005c8f from the image, not the background color.
    type: 'dark',
  },
  {
    name: 'Nature Fresh',
    fontFamily: 'Montserrat, sans-serif',
    fontColor: '#1b4332',
    backgroundColor: '#e8f5e9',
    slideBackgroundColor: '#ffffff',
    accentColor: '#4caf50',
    gradientBackground: 'linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)',
    navbarColor: '#c8e6c9',
    sidebarColor: '#e8f5e9',
    type: 'light',
  },
  {
    name: 'Tech Vibrant',
    fontFamily: '"Roboto", sans-serif',
    fontColor: '#ffffff',
    backgroundColor: '#2c3e50',
    slideBackgroundColor: '#34495e',
    accentColor: '#e74c3c',
    gradientBackground: 'linear-gradient(135deg, #3498db 0%, #2c3e50 100%)', // Note: Gradient start color is #3498db from the image.
    navbarColor: '#34495e',
    sidebarColor: '#2c3e50',
    type: 'dark',
  },
  {
    name: 'Default',
    fontFamily: '"Inter", sans-serif',
    fontColor: '#000000',
    backgroundColor: '#f0f0f0',
    slideBackgroundColor: '#ffffff',
    accentColor: '#3b82f6',
    navbarColor: '#ffffff',
    sidebarColor: '#f0f0f0',
    type: 'light',
  },
  {
    name: 'Dark Elegance',
    fontFamily: '"Playfair Display", serif',
    fontColor: '#ffffff',
    backgroundColor: '#1a1a1a',
    slideBackgroundColor: '#2c2c2c',
    accentColor: '#ffd700',
    gradientBackground: 'linear-gradient(135deg, #2c2c2c 0%, #1a1a1a 100%)',
    navbarColor: '#2c2c2c',
    sidebarColor: '#1a1a1a',
    type: 'dark',
  },
];

